### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by websupergirl** [UmmuRasul/x-team-internship#1]
If you go to the repo, you should see a button that says "add a readme". Click it and make one!

For now, you may just want to include some basics like the purpose of the project and what language it is in. Later, you'll want to add some more information about the specific project you're working on and how to run it.

Here is a good discussion of what goes into a readme file:
https://github.com/EugeneCodeCamp/EugeneCodeCamp.github.io/issues/8

**Comment by websupergirl** [comment]
Also @UmmuRasul ... when you are taking a task in Github, use the tools on the right side of the screen to assign yourself the task. It is a good habit to get into.

Once the readme is established, you'll want to set it up the project to edit it on your computer by cloning it, and then push your completed readme back to the repo.

**Comment by UmmuRasul** [comment]
great!
I'll make use of the Github tools
